---
- hosts: j5
  gather_facts: true
  connection: local

  tasks:
   - name: show run
     ios_command:
       commands:
         - show run
       host: "{{ ansible_host }}"
       username: ansible
       password: ansible
     register: config

   - name: save output to /home/jviveiros/ansible/configs/
     copy: 
       content: "{{ config.stdout[0] }}"
       dest: "/home/jviveiros/ansible/configs/{{ inventory_hostname }}_{{ ansible_date_time.date }} {{ ansible_date_time.time }}.txt"

